# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd5f5573f8c43fb8e07e133293142cb133a9b6dcf5a51c3ed9c769245042781523602b462d1b935f11c7bcc982b8863ccc00bc2fafaa2d3a08c39afcbe99795e

test:
  secret_key_base: 6cb23b55114d2a0b83269579eb6394eef22c403bf65596c4266323669cffb7d61ddee9c646719cbba82b70e7c8125917c75eff4e1e15aba4d2a8ef8b8d5a28fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
